#----------------------------------------------------------
# config
#----------------------------------------------------------

whisper_model:  large-v2 # select Whisper model or local path
SAMPLE_RATE:    16000
INTERVAL:       3
BUFFER_SIZE:    4096
OrganizationID:         # OpenAI Organization ID
OpenAIapikey :          # OpenAI API Key
phrase_timeout: 3
record_timeout: 3
